### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by GravisZro** [Hoernchen/Epiphany#2]
It seems this backend is a bit out of date with LLVM itself because it no longer builds.
- In Epiphany.td, the type SubRegIndex is now a template with a mandatory argument.  I just guessed it's 32.
- After that it goes kaput and spits out:
  `
  llvm-tblgen: StringMatcher.cpp:52: bool llvm::StringMatcher::EmitStringMatcherForChar(const std::vector<const std::pair<std::basic_string<char>, std::basic_string<char> >*>&, unsigned int, unsigned int) const: Assertion `Matches.size() == 1 && "Had duplicate keys to match on"' failed.
  `

I hope you will update it!

**Comment by Hoernchen** [comment]
It's not surprising that it doesn't build, even this version is half-broken (reg combine for fma) due to the fact that yabin hu rebased it to a slightly newer version.
I don't have the time to fix this.

There is a matching llvm version here : https://github.com/Hoernchen/llvm/tree/epiphany
